"""Qwen3.8-27B artifact conversion target."""

from .inventory import (
    ALIAS_SPECS,
    FORMAT_COUNTS,
    HUIHUI_ABLITERATED_MODEL_ID,
    LAYOUT_COUNTS,
    LOGICAL_ROW_VIEW_SPECS,
    MODEL_ID,
    MODEL_IDS,
    OBJECT_SPECS,
    RESOURCE_SPECS,
    TARGET_KEY,
    TENSOR_SPECS,
)

__all__ = [
    "ALIAS_SPECS",
    "FORMAT_COUNTS",
    "HUIHUI_ABLITERATED_MODEL_ID",
    "LAYOUT_COUNTS",
    "LOGICAL_ROW_VIEW_SPECS",
    "MODEL_ID",
    "MODEL_IDS",
    "OBJECT_SPECS",
    "RESOURCE_SPECS",
    "TARGET_KEY",
    "TENSOR_SPECS",
]
