#include "models/qwen3_5/frontend/structured_output.h"

#include "models/qwen3_5/frontend/tokenizer.h"

#include <xgrammar/compiler.h>
#include <xgrammar/grammar.h>
#include <xgrammar/matcher.h>
#include <xgrammar/tokenizer_info.h>

#include <algorithm>
#include <cstdint>
#include <exception>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>

namespace ninfer::models::qwen3_5::frontend {

struct CompiledOutputFormat {
    xgrammar::CompiledGrammar grammar;
};

namespace {

constexpr std::string_view kThinkClose = "</think>";

// Qwen closes its reasoning with "</think>\n\n", and the canonical thinking-control suffix ends
// the same way, so the JSON value may follow up to two whitespace characters. Longer leading
// whitespace is refused: an unbounded run is the classic way a constrained model stalls.
constexpr const char* kLeadingWhitespaceGrammar =
    R"(root ::= "" | [ \t\n\r] | [ \t\n\r] [ \t\n\r])";

// Whitespace between JSON tokens is free-form (the model may pretty-print), but a single run is
// bounded for the same reason as the leading whitespace above.
constexpr int kMaximumWhitespaceRun = 32;

// Long enough to undo any speculative window (the largest draft window is 15 tokens).
constexpr int kMaximumRollbackTokens = 64;

constexpr std::size_t kCompilerCacheBytes = std::size_t{256} << 20;

std::size_t longest_marker_prefix_suffix(std::string_view text) {
    const std::size_t maximum = std::min(text.size(), kThinkClose.size());
    for (std::size_t size = maximum; size != 0; --size) {
        if (text.substr(text.size() - size) == kThinkClose.substr(0, size)) { return size; }
    }
    return 0;
}

// Tracks whether the Qwen reasoning section is still open, from the generated bytes.
struct ReasoningGate {
    bool open = false;
    std::string pending;

    void feed(std::string_view bytes) {
        if (!open || bytes.empty()) { return; }
        pending.append(bytes);
        if (pending.find(kThinkClose) != std::string::npos) {
            pending.clear();
            open = false;
            return;
        }
        pending.erase(0, pending.size() - longest_marker_prefix_suffix(pending));
    }
};

void fill_all(std::span<std::uint32_t> mask) { std::fill(mask.begin(), mask.end(), ~0U); }

} // namespace

struct StructuredOutputCompiler::State {
    State(xgrammar::TokenizerInfo info_, int vocab)
        : info(std::move(info_)), compiler(info, 8, true, static_cast<std::int64_t>(kCompilerCacheBytes)),
          vocab_size(vocab) {}

    xgrammar::TokenizerInfo info;
    xgrammar::GrammarCompiler compiler;
    int vocab_size = 0;
};

StructuredOutputCompiler::StructuredOutputCompiler(std::shared_ptr<const Tokenizer> tokenizer)
    : tokenizer_(std::move(tokenizer)) {
    if (!tokenizer_) { throw std::invalid_argument("structured output requires a tokenizer"); }
}

StructuredOutputCompiler::~StructuredOutputCompiler() = default;

StructuredOutputCompiler::State& StructuredOutputCompiler::state() const {
    std::call_once(state_once_, [this] {
        const auto vocab = static_cast<int>(tokenizer_->vocab_size());
        // Control-vocabulary tokens (chat markers, `<think>`, tool and vision tags) are never part
        // of a JSON value; an empty entry tells XGrammar never to license them. The model's stop
        // tokens are supplied per matcher, where the grammar licenses them only once the value is
        // complete.
        std::vector<std::string> vocabulary(static_cast<std::size_t>(vocab));
        for (int id = 0; id < vocab; ++id) {
            if (!tokenizer_->is_valid_token(id) || tokenizer_->is_added_token(id) ||
                tokenizer_->is_special_token(id)) {
                continue;
            }
            vocabulary[static_cast<std::size_t>(id)] = std::string(tokenizer_->decoded_token(id).bytes);
        }
        const std::vector<int> stops(tokenizer_->default_stop_token_ids().begin(),
                                     tokenizer_->default_stop_token_ids().end());
        state_ = std::make_unique<State>(
            xgrammar::TokenizerInfo(vocabulary, xgrammar::VocabType::RAW, vocab, stops), vocab);
    });
    return *state_;
}

std::shared_ptr<const CompiledOutputFormat>
StructuredOutputCompiler::compile(const OutputFormat& format) const {
    if (format.kind == OutputFormatKind::Text) {
        throw std::logic_error("text output has no structured-output grammar");
    }
    State& compiler = state();
    try {
        // json_object is the schema of an arbitrary object under standard (non-strict) defaults.
        const std::string schema =
            format.kind == OutputFormatKind::JsonObject ? std::string(R"({"type":"object"})")
                                                        : format.json_schema;
        const bool strict = format.kind == OutputFormatKind::JsonSchema && format.strict;
        const xgrammar::Grammar value = xgrammar::Grammar::FromJSONSchema(
            schema, true, std::nullopt, std::nullopt, strict, kMaximumWhitespaceRun);
        const xgrammar::Grammar grammar = xgrammar::Grammar::Concat(
            {xgrammar::Grammar::FromEBNF(kLeadingWhitespaceGrammar), value});
        return std::make_shared<const CompiledOutputFormat>(
            CompiledOutputFormat{compiler.compiler.CompileGrammar(grammar)});
    } catch (const RequestError&) { throw; } catch (const std::exception& error) {
        throw RequestError(RequestErrorKind::InvalidOutputFormat,
                           std::string("output format cannot be enforced: ") + error.what());
    }
}

struct StructuredOutputConstraint::State {
    State(const xgrammar::CompiledGrammar& grammar, std::vector<int> stops, bool reasoning)
        : matcher(std::in_place, grammar, std::move(stops), false, kMaximumRollbackTokens) {
        gate.open = reasoning;
    }

    State(const State& other) : matcher(std::in_place, other.matcher->Fork()), gate(other.gate) {}

    std::optional<xgrammar::GrammarMatcher> matcher;
    ReasoningGate gate;
};

StructuredOutputConstraint::StructuredOutputConstraint(
    std::shared_ptr<const Tokenizer> tokenizer, std::shared_ptr<const CompiledOutputFormat> format,
    std::vector<TokenId> stop_tokens, bool starts_in_reasoning)
    : tokenizer_(std::move(tokenizer)) {
    if (!tokenizer_ || !format) {
        throw std::invalid_argument("structured output constraint requires a compiled format");
    }
    committed_ = std::make_unique<State>(
        format->grammar, std::vector<int>(stop_tokens.begin(), stop_tokens.end()),
        starts_in_reasoning);
}

StructuredOutputConstraint::~StructuredOutputConstraint() = default;

void StructuredOutputConstraint::begin_preview() {
    preview_ = std::make_unique<State>(*committed_);
}

bool StructuredOutputConstraint::preview_token(TokenId token) {
    if (!preview_) { throw std::logic_error("structured output has no open preview"); }
    State& state = *preview_;
    if (!tokenizer_->is_valid_token(token)) { return false; }
    if (state.gate.open) {
        state.gate.feed(tokenizer_->decoded_token(token).bytes);
        return true;
    }
    return !state.matcher->IsTerminated() && state.matcher->AcceptToken(token);
}

void StructuredOutputConstraint::commit_preview() noexcept {
    if (preview_) { committed_ = std::move(preview_); }
}

bool StructuredOutputConstraint::fill_token_masks(std::span<const TokenId> speculative,
                                                  std::uint32_t columns,
                                                  std::span<std::uint32_t> masks,
                                                  std::size_t words_per_mask) {
    const auto vocab = static_cast<std::size_t>(tokenizer_->vocab_size());
    if (columns == 0 || columns > speculative.size() + 1U ||
        words_per_mask < (vocab + 31U) / 32U ||
        masks.size() < static_cast<std::size_t>(columns) * words_per_mask) {
        throw std::invalid_argument("structured-output mask request has an invalid geometry");
    }
    xgrammar::GrammarMatcher& matcher = *committed_->matcher;
    ReasoningGate gate                = committed_->gate;
    std::int64_t bitmask_words        = static_cast<std::int64_t>(xgrammar::GetBitmaskSize(
        static_cast<int>(vocab)));
    bool restricted = false;
    bool reachable  = true;
    int accepted    = 0;
    for (std::uint32_t column = 0; column < columns; ++column) {
        const std::span<std::uint32_t> mask =
            masks.subspan(static_cast<std::size_t>(column) * words_per_mask, words_per_mask);
        if (!reachable || gate.open || matcher.IsTerminated()) {
            fill_all(mask);
        } else {
            std::fill(mask.begin() + static_cast<std::ptrdiff_t>(bitmask_words), mask.end(), 0U);
            DLTensor tensor{};
            tensor.data   = mask.data();
            tensor.device = DLDevice{kDLCPU, 0};
            tensor.ndim   = 1;
            tensor.dtype  = xgrammar::GetBitmaskDLType();
            tensor.shape  = &bitmask_words;
            restricted    = matcher.FillNextTokenBitmask(&tensor) || restricted;
        }
        if (column >= speculative.size() || !reachable) { continue; }
        const TokenId token = speculative[column];
        if (!tokenizer_->is_valid_token(token)) {
            reachable = false;
        } else if (gate.open) {
            gate.feed(tokenizer_->decoded_token(token).bytes);
        } else if (!matcher.IsTerminated() && matcher.AcceptToken(token)) {
            ++accepted;
        } else {
            // This speculative token will be rejected at this column, so later columns are never
            // consumed.
            reachable = false;
        }
    }
    if (accepted != 0) { matcher.Rollback(accepted); }
    return restricted;
}

} // namespace ninfer::models::qwen3_5::frontend
